### ISSUE TITLE
Kinfu action client question

### ISSUE THREAD

**Issue by egeldres** [RMonica/ros_kinfu#8]
Hi again RMonica,

I'm slowly understanding in this great project, now with a specific doubt. 
I made an action client that connects to the kinfu action server, but I'm not sure if the following use is the intended.
My client is making a request for just sensor pointcloud publications, but the answer I found it's published to 
/kinfu_output/actions/request/result 

the message is "kinfu_msg" type with the full structure is clean excluding the pointcloud, and it's similar to all of this in one message:
KinfuRequestHeader tsdf_header
std_msgs/Header header
sensor_msgs/PointCloud2 pointcloud
pcl_msgs/PolygonMesh mesh
sensor_msgs/Image image
std_msgs/Float32MultiArray float_values
std_msgs/UInt64MultiArray uint_values

What I was trying to get is to publish just a "sensor_msgs/PointCloud2" message the way I can see it through rviz.
 It's already implemeted? or do I need to build a node to separate the "kinfu_msg" structure?

Many thanks in advance

**Comment by RMonica** [comment]
Hi egeldres.

The action interface is meant to be used with an action client, usually (if you are using C++) SimpleActionClient:
  http://wiki.ros.org/actionlib_tutorials/Tutorials/SimpleActionClient
  http://docs.ros.org/jade/api/actionlib/html/classactionlib_1_1SimpleActionClient.html
You aren't supposed to access directly the internal topics such as `/kinfu_output/actions/request/result`.

Once the action completes, you can do something like:
```
  sensor_msgs::PointCloud2 pointcloud = ac.getResult()->pointcloud;
```
if you are expecting a pointcloud, or
```
  pcl_msgs::PolygonMesh mesh = ac.getResult()->mesh;
```
if you are expecting a mesh, and so on. 
All the fields (mesh, pointcloud, etc.) are included in the response, but only the field that you requested will be populated.

From there, do what you want with the pointcloud.
For example, you could publish it to a topic connected to RViz.

**Comment by egeldres** [comment]
Many thanks my client worked.

But the poincloud2 publisher and the automatic /kinfu_output.../result, are sending empty pointclouds, all the xyz coordinates are 0,0,0, even when I'm seeing  the built world in the /kinfu_current_view

The message when extracting pointcloud is the one pasted below:

Comments
world contains 0 points after update: if I request again it's not 0, but the pcl it's still empty
world contains 0 points after cleaning: same as update.

[ INFO] [1491181324.652992345]: Avg frame time = 41.64 ms (24.02 fps)
[ INFO] [1491181325.178585824]: kinfu_output: executing new request action, id 0.
[ INFO] [1491181325.179187756]: kinfu: Extract Cloud Worker started.
[ INFO] [1491181325.179265585]: kinfu: Locking kinfu...
[ INFO] [1491181325.223652819]: kinfu: Locked.
Extracting current volume...The old cube's metric origin was    (0.000000, 0.000000, 0.000000).
The new cube's metric origin is now (-0.000416, -0.005962, -0.000227).
 SIZE IS 783062
shift: downloading weights...
shift: weights downloaded.
world contains 0 points after update
world contains 0 points after cleaning
[ INFO] [1491181325.955397663]: kinfu: retrieveOldCube: scheduled old cube.
shift: calling weight listener...
shift: done.
Done
[ INFO] [1491181325.955773112]: kinfu: RetrieveCubeWorker: working...
[ INFO] [1491181325.963987012]: kinfu: Marching cubes...
Getting world as cubes. World contains 783062 points.
World contains 783062 points after nan removal.
cube size is set to 512
Bounding box for the world: 
	 [12.000000 - 364.000000] 
	 [23.000000 - 330.000000] 
	 [47.000000 - 511.000000] 
Extracting cube at: [12.000000, 23.000000, 47.000000].
returning 1 cubes
Processing world with volume size set to 3meters
[ INFO] [1491181326.098207322]: kinfu: RetrieveCubeWorker: retrieved 0 voxels.
[ INFO] [1491181326.098296763]: kinfu: NewCubeWorker: Setting known voxels...

[ INFO] [1491181326.116364432]: kinfu: retrieveOldCube: returned old cube.
known: uploading weights...
known: upload complete.
There are 1 cubes to be processed 
Processing cube number 0
VOLUME SIZE IS 3
[ INFO] [1491181327.202381784]: Avg frame time = 53.85 ms (18.57 fps)
Done!
[ INFO] [1491181327.213737548]: kinfu: Extracting only points from mesh...
[ INFO] [1491181327.255670354]: kinfu: Merging points...
[ INFO] [1491181327.281582024]: kinfu: A custom transformation will be applied.
[ INFO] [1491181327.281655422]: kinfu: Applying transformation...
[ INFO] [1491181327.314686268]: kinfu: Publishing...
[ INFO] [1491181327.314753052]: kinfu_output: 
Received response with
    1084812 cloud points
    0 mesh cloud points
    0 triangles
    0 pixels
    0 uint64 values
    0 float32 values

[ INFO] [1491181327.314811842]: kinfu_output: result sent for id 0
[ INFO] [1491181327.352003036]: kinfu: Extract Cloud Worker complete.
[ INFO] [1491181327.543157020]: kinfu: NewCubeWorker: Done: set 8127534 leaves.
[ INFO] [1491181327.543238984]: kinfu: NewCubeWorker: points are 8127534, bitmasks are 21470, full bitmasks are 0.
[ INFO] [1491181328.606057673]: Avg frame time = 41.73 ms (23.97 fps)
[ INFO] [1491181329.987845922]: Avg frame time = 41.00 ms (24.39 fps)
[ INFO] [1491181331.376414145]: Avg frame time = 41.33 ms (24.19 fps)


the data echo shows the message as many zeroes, I think it's really empty.

1, 190, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 63, 239, 56, 100, 191, 236, 203, 148, 187, 249, 240, 231, 190, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 63, 239, 56, 100, 191, 236, 203, 148, 187, 249, 240, 231, 190, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 63, 213, 213, 91, 191, 151, 205, 89, 190, 92, 177, 238, 190, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 63, 213, 213, 91, 191, 151, 205, 89, 190, 92, 177, 238, 190, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 63, 213, 213, 91, 191, 151, 205, 89, 190, 92, 177, 238, 190, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 63, 182, 84, 93, 191, 59, 115, 48, 62, 243, 174, 241, 190, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 63, 182, 84, 93, 191, 59, 115, 48, 62, 243, 174, 241, 190, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 63, 182, 84, 93, 191, 59, 115, 48, 62, 243, 174, 241, 190, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

I'm not sure if the marching cubes It's really fixed or if it's my build.

Many thanks in advance

**Comment by RMonica** [comment]
The log says:
```
  kinfu: A custom transformation will be applied.
```
What transformation are you sending?

**Comment by egeldres** [comment]
I'm not really sure, I'm requesting the pointcloud with everything false:

  goal.request.tsdf_header.request_type = kinfu_msgs::KinfuRequestHeader::REQUEST_TYPE_GET_CLOUD; //PCL

  goal.request.tsdf_header.request_source_name = "/kinfu1_response_topic";
   goal.request.request_reset = false;
  goal.request.request_transformation = false;
  goal.request.request_bounding_box = false;
  goal.request.request_sphere = false;
  goal.request.request_subsample = false;
  goal.request.request_bounding_box_view=false;
  goal.request.tsdf_center_distance=0.0;
  goal.request.request_camera_intrinsics=false;
  goal.request.request_view_poses=false;
  goal.request.request_remove_duplicates=false;

  client.sendGoal(goal);

**Comment by egeldres** [comment]
Many thanks again, my fail was that:
request_transformation = true;
tsdf_center_distance=10.0;
changed that to
request_transformation = false;
tsdf_center_distance=0.0;

Now it works perfectly.

You can close this issue.

**Comment by RMonica** [comment]
Ok. Thank you.
